Generate tasks
ogihara-ryo/zone pull request #6
Opened 2019-09-29 15:30 UTC by Chi-rr

2019-09-29 17:54 UTC, ryo-ryukalice requested changes

2019-09-29 17:54 UTC, ogihara-ryo commented on db/migrate/20190926085346_create_tasks.rb
> +      t.boolean :finished
`default: false, null: false` を追加してください。

2019-10-01 05:46 UTC, Chi-rr commented on db/migrate/20190926085346_create_tasks.rb
> +      t.boolean :finished
追加完了です。

2019-10-07 13:48 UTC, ryo-ryukalice requested changes

2019-10-07 13:48 UTC, ogihara-ryo commented on db/migrate/20190926085346_create_tasks.rb
> +      t.integer :user_id
`t.belongs_to :user_id, index: true`

2019-10-08 18:03 UTC, ryo-ryukalice approved these changes

2019-10-08 18:03 UTC, merged